version: '3.8'

services:
  publisher:
    image: camptocamp/reims_publisher:latest
    volumes:
      - ./reims_publisher/reims_publisher:/app/reims_publisher
    command: publish

  tester:
    image: camptocamp/reims_publisher:latest
    volumes:
      - ./reims_publisher/reims_publisher:/app/reims_publisher
      - ./reims_publisher:/src
    command: pytest -vv /src/tests
