---

name: Continuous integration

on:
  push:

jobs:
  main:
    name: Continuous integration
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v1

      - name: Build
        run: make build

      - name: Lint
        run: make checks

      - name: Tests
        run: |
          make up
          make tests

      - name: Docker compose logs
        if: ${{ always() }}
        run: |
          docker-compose logs

      - name: Clean
        run: make clean
